"""
Django settings for Workspace project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ
import json
from .base import *
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/
env = environ.Env()
environ.Env.read_env("Workspace/.env")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY_DEV')
# AUTH_USER_MODEL="User"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG_DEV', default=False)

allowed_hosts=env.str("ALLOWED_HOSTS_DEV")
ah=allowed_hosts.split(",")

ALLOWED_HOSTS = ah #['localhost','40.80.81.211','firstcourse.in','www.firstcourse.in']


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env.str('DB_NAME_DEV'),#smart_accounting casmart
        'USER': env.str('DB_USER_DEV'),
        'PASSWORD': env.str('DB_PASSWORD_DEV'),
        'HOST': env.str('DB_HOST_DEV'),
        'PORT': env.str('DB_PORT_DEV'),
    },
}


#Static files hosted on S3
AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY')

SENDGRID_API_KEY = env.str('SENDGRID_FC_SECRET')

EMAIL_HOST_PASSWORD = SENDGRID_API_KEY






CLIENT_ID = env.str('QB_CLIENT_ID_DEV')
CLIENT_SECRET = env.str('QB_CLIENT_SECRET_DEV')
REDIRECT_URI = env.str('REDIRECT_URI_DEV')
SANDBOX_QBO_BASEURL = env.str('SANDBOX_QBO_BASEURL_DEV')


DBBACKUP_STORAGE_OPTIONS = {
    'access_key': AWS_ACCESS_KEY_ID,
    'secret_key': AWS_SECRET_ACCESS_KEY,
    'bucket_name': 'firstcourse-db-backups',
    'default_acl': 'private',
}

CELERY_BROKER_URL=env.str('CELERY_BROKER_URL_DEV')

JSREPORTENGINE_HOST=env.str("JSREPORT_HOST_DEV")
JSREPORTENGINE_PORT=env.str("JSREPORT_PORT_DEV")
JSREPORTENGINE_DATA=env.str("JSREPORT_DATA_DEV")

EXPRESS_API_HOST=env.str("EXPRESS_API_HOST_DEV")
EXPRESS_API_PORT=env.str("EXPRESS_API_PORT_DEV")
